### ISSUE TITLE
Advanced log collection refers to old data structures

### ISSUE THREAD

**Issue by kbreit** [DataDog/documentation#10226]
The advanced log collection documentation (https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=configurationfile) shows the following example. However, the data structures from the agent and documentation don't appear to match. Documentation shows `logs[].log_processing_rules` and the config file shows `logs_config.processing_rules`.

```
logs:
  - type: file
    path: /my/test/file.log
    service: cardpayment
    source: java
    log_processing_rules:
    - type: exclude_at_match
      name: exclude_datadoghq_users
      ## Regexp can be anything
      pattern: \w+@datadoghq.com
```

However, it appears the `/etc/datadog-agent/datadog.yaml` file is showing the following structure.

```
logs_enabled: true
logs_config:
  processing_rules:
  ...
```
