### ISSUE TITLE
Documentation on how to get Datadog and serverless with serverless esbuild working

### ISSUE THREAD

**Issue by CorruptedHeart** [DataDog/documentation#14027]
**Is your feature request related to a problem? Please describe.**
When using the Serverless Datadog layer developers mustn't include the `dd-trace` or `datadog-lambda-js` packages.

If they do, then they will see `datadog:handler not initialized` in the Cloudwatch logs (if running on AWS).

**Describe the solution you'd like**
A page describing how to setup serverless-esbuild to not include those packages.

The correct handling is to not mark `dd-trace` and `datadog-lambda-js` as external but rather as exclude under serverless-esbuild's options.

```yaml
custom:
  esbuild:
    external: ["pg", "knex"]
    exclude: ["dd-trace", "datadog-lambda-js"]
```

**Describe alternatives you've considered**
The webpack compatibility page was consulted as a potential fix but did not provide any change.
