### ISSUE TITLE
DBM documentation YAML configurationn for Helm is invalid

### ISSUE THREAD

**Issue by caramcc** [DataDog/documentation#24699]
## Documentation Page

From grepping this repo, this seems to appear on most (if not all) all setup pages under `database_monitoring` — for example [setup mysql aurora](https://github.com/DataDog/documentation/blob/master/content/en/database_monitoring/setup_mysql/aurora.md?plain=1#L268)

## Issue Description

Given configuration block uses an invalid YAML block scalar operator, `-|`, which results in syntax errors when copying. I suspect `|-` was the intended block scalar operator.

Additionally, the indentation for the configuration keys is incorrect — `instances` is indented too far. This results in a `Configuration file contains no valid instances` error.

**Expected:**
```
clusterAgent:
  confd:
    mysql.yaml: -|
      cluster_check: true
      init_config:
      instances:
        - dbm: true
          host: <INSTANCE_ADDRESS>
          port: 3306
          username: datadog
          password: 'ENC[datadog_user_database_password]'      

clusterChecksRunner:
  enabled: true
```

**Actual:**
```
clusterAgent:
  confd:
    mysql.yaml: -|
      cluster_check: true
      init_config:
        instances:
          - dbm: true
            host: <INSTANCE_ADDRESS>
            port: 3306
            username: datadog
            password: 'ENC[datadog_user_database_password]'      

clusterChecksRunner:
  enabled: true
```
