### ISSUE TITLE
Invalid example on Kubernetes Prometheus and OpenMetrics metrics collection page

### ISSUE THREAD

**Issue by RLProteus** [DataDog/documentation#24950]
## Documentation Page
[Kubernetes Prometheus and OpenMetrics metrics collection](https://github.com/DataDog/documentation/blob/master/content/en/containers/kubernetes/prometheus.md)

## Issue Description
The [Advanced configuration](https://docs.datadoghq.com/containers/kubernetes/prometheus/?tab=kubernetesadv2#advanced-configuration) example incorrectly uses a map for `additionalConfigs` when that field only supports the string type as defined [here](https://github.com/DataDog/datadog-operator/blob/main/apis/datadoghq/v2alpha1/datadogagent_types.go#L865). Also see the example [here](https://github.com/DataDog/datadog-operator/blob/main/examples/datadogagent/datadog-agent-with-prometheus-autodiscovery-advanced-config.yaml#L10).

Current doc:
```
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    credentials:
      apiKey: <DATADOG_API_KEY>

  features:
    prometheusScrape:
      enabled: true
      enableServiceEndpoints: true
      additionalConfigs:
        - autodiscovery:
            kubernetes_container_names:
              - my-app
            kubernetes_annotations:
              include:
                app: my-app
          configurations:
            - timeout: 5
              send_distribution_buckets: true
```

Should be updated to:
```
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    credentials:
      apiKey: <DATADOG_API_KEY>

  features:
    prometheusScrape:
      enabled: true
      enableServiceEndpoints: true
      additionalConfigs: |-
        - autodiscovery:
            kubernetes_container_names:
              - my-app
            kubernetes_annotations:
              include:
                app: my-app
          configurations:
            - timeout: 5
              send_distribution_buckets: true
```
