### ISSUE TITLE
PostgreSQL documentation

### ISSUE THREAD

**Issue by madrobby** [DataDog/documentation#264]
The documentation for the PostgreSQL is severely lacking and doesn't even include an example (it links to one off-site).

The examples given fail to mention that the `dbname` parameter must be specified in order to track relation metrics, and that the connection to PostgreSQL will be made to that specific database—which will fail when everything else is configured as documented, as the datadog user will not have access to that database.

It's still unclear to me what rights/grants the datadog user needs to successfully track metrics for relations. Could you please expand the documentation to include this information and have a more fleshed out example?

**Comment by technovangelist** [comment]
Hi Thomas,,

I am looking into the issues you mentioned. Are you still working with Datadog?

**Comment by madrobby** [comment]
@technovangelist I do! This is our config rn:

```yaml
init_config:

instances:
  - host: localhost
    port: 5432
    username: datadog
    password: (datadog postgresql password)
    dbname: (database name)
    relations:
      - table1
      - table2
      - table3
```

We create the required user with this ansible action:

```yaml
- name: Configure PostgreSQL Datadog user
  sudo: yes
  sudo_user: postgres
  shell: >
    psql -d freckle -c "CREATE USER datadog WITH PASSWORD '{{ datadog_postgresql_password }}'; GRANT SELECT ON pg_stat_database TO datadog;"
  ignore_errors: yes
  when: datadog_key is defined
```
