### ISSUE TITLE
AKS kubelet configuration issue

### ISSUE THREAD

**Issue by samcook** [DataDog/documentation#29042]
## Documentation Page

`content/en/containers/kubernetes/distributions.md`

## Issue Description

The documentation for configuring the kubelet host on AKS when using the Datadog Operator specifies the following:
```yaml
spec:
  global:
    ...
    kubelet:
      host:
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
```

I get the following error when trying to use that configuration:
```
strict decoding error: unknown field "spec.global.kubelet.host.valueFrom"
```

Removing `valueFrom` seems to solve it for me:
```yaml
spec:
  global:
    ...
    kubelet:
      host:
        fieldRef:
          fieldPath: spec.nodeName
```
